[module]
name = "87606_408lf"
entry = "87606_408lf.ato:87606408lf"
tags = []
description = "16 Position Receptacle Connector 0.100" (2.54mm) Through Hole Tin"
datasheet = "https://cdn.amphenol-cs.com/media/wysiwyg/files/drawing/87606.pdf"