[module]
name = "C25yxj100m5x11"
entry = "C25yxj100m5x11.ato:25yxj100m5x11"
tags = []
description = "Rubycon 100uF 25 V dc Aluminium Electrolytic Capacitor, YXJ Series 5000h 5 Dia. x 11mm"
datasheet = "http://www.rubycon.co.jp/en/catalog/e_pdfs/aluminum/e_yxj.pdf"